services:
  - type: web
    name: web3_mud
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromDatabase:
          name: redis
          property: connectionString
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: redis
    plan: free
    type: redis

